In [4]:
import numpy as np

1. What is a Python library? Why ^o we use Python libraries?

In [ ]:
Python library is a collection of functions. We use libraries because they 

 What is the difference between Numpy array and List?

Numpy contains homogenous data while list can contain hetrogenrous data. Numpy is faster than list. Numpy supports various mathematical operations compared to list. 

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [9]:
arr.shape, arr.size, arr.ndim

((3, 4), 12, 2)

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [10]:
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [12]:
arr1[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [14]:
arr1[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [70]:
for i in range(arr1.shape[0]):
    if i%2==0:
        continue
    else:
        for j in range(arr1.shape[1]):
            if j%2==0:
                continue
            else:
                print(arr1[i,j])
        

6
8


In [71]:
arr1.shape[0]

3

How can you generate a random 3x3 matrix with values between 0 and 1?

In [17]:
np.random.rand(3,3)

array([[0.31908758, 0.02552587, 0.71139161],
       [0.34364466, 0.60431089, 0.59849809],
       [0.76567959, 0.33929028, 0.43392663]])

8. Describe the difference between np.random.rand and np.random.randn?

Ans : np.random.rand generates random values from uniform distribution where as np.random.randn generates values from standard normal distribution

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [19]:
arr1.ndim

2

In [58]:
arr2=np.expand_dims(arr1, axis = 0)

In [59]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [60]:
arr2.shape

(1, 3, 4)

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [24]:
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [26]:
mat1=arr1.copy()
mat2=arr1.copy()

In [27]:
mat1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
#index wise multiplication
mat1*mat2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [32]:
#matrix Mutliplication
mat1 @ mat2

#this is not possible as row of mat2 is not equal to column of mat1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [33]:
 mat1+mat2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [34]:
mat1-mat2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
mat2/mat1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte order of an array?

The byteswap() function in Numpy can be used to swap the byte order of an array. It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.

In [36]:
arr3=arr1.byteswap()

In [37]:
arr3

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

13.  What is the significance of the np.linalg.inv function?

It is used to calculate the inverse of a matrix

14. What does the np.reshape function do, and how is it used?

np.reshape() is used to change the shape of an array to any desired shape. arr1 original shape is 3,4 but we can use rehsape function to make it an araay of size 2,6



In [43]:
arr1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

15. What is broadcasting in Numpy?

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [44]:
arr = np.zeros((3, 4))

In [45]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])